apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8s-cluster
  region: us-west-1

nodeGroups:
  - name: main-ng
    instanceType: t2.micro
    desiredCapacity: 2
    ssh:
      allow: true
