apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  labels:
    app: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: amrhashem/service1:k8s.v2.latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  type: NodePort
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080