apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-deployment
  labels:
    app: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: amrhashem/service2:k8s.v1.3
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  type: NodePort
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090